# config/config.yaml
hdfs:
  base_dir: "hdfs://localhost:9000/user/sources"
  sample_size: 5
  defaultFS: "hdfs://localhost:9000"

hive:
  host: "localhost"
  port: 10000
  database: "default"
  metadata_table: "metadata"

llm:
  model_name: "gpt-4o"

openai:
  api_key: "ENV_VAR"
  model_name: "gpt-4o"